# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter_hq"
    static_configs:
      - targets:
          - "10.0.0.4:9100"
          - "10.0.0.5:9100"
          - "10.0.0.6:9100"
          - "10.0.0.20:9100"
          - "10.0.0.30:9100"
          - "10.0.0.100:9100"
        labels:
          site: "hq"

  - job_name: "node_exporter_dr"
    static_configs:
      - targets:
          - "10.1.0.4:9100"
          - "10.1.0.5:9100"
          - "10.1.0.6:9100"
          - "10.1.0.20:9100"
          - "10.1.0.30:9100"
          - "10.1.0.100:9100"
        labels:
          site: "dr"

  - job_name: "postgres_exporter_hq"
    static_configs:
      - targets: ["10.0.0.4:9187", "10.0.0.5:9187", "10.0.0.6:9187"]
        labels:
          site: "hq"

  - job_name: "postgres_exporter_dr"
    static_configs:
      - targets: ["10.1.0.4:9187", "10.1.0.5:9187", "10.1.0.6:9187"]
        labels:
          site: "dr"

  - job_name: "haproxy_exporter_hq"
    static_configs:
      - targets: ["10.0.0.100:9101"]
        labels:
          site: "hq"

  - job_name: "haproxy_exporter_dr"
    static_configs:
      - targets: ["10.1.0.100:9101"]
        labels:
          site: "dr"

  - job_name: "etcd_hq"
    metrics_path: /metrics
    static_configs:
      - targets: ["10.0.0.4:2379", "10.0.0.5:2379", "10.0.0.6:2379"]
        labels:
          site: "hq"

  - job_name: "etcd_dr"
    metrics_path: /metrics
    static_configs:
      - targets: ["10.1.0.4:2379", "10.1.0.5:2379", "10.1.0.6:2379"]
        labels:
          site: "dr"

  - job_name: "patroni_hq"
    metrics_path: /metrics
    basic_auth:
      username: 'patroni'
      password: 'PATRONI_PASSWORD'
    static_configs:
      - targets: ["10.0.0.4:8008", "10.0.0.5:8008", "10.0.0.6:8008"]
        labels:
          site: "hq"

  - job_name: "patroni_dr"
    metrics_path: /metrics
    basic_auth:
      username: 'patroni'
      password: 'PATRONI_PASSWORD'
    static_configs:
      - targets: ["10.1.0.4:8008", "10.1.0.5:8008", "10.1.0.6:8008"]
        labels:
          site: "dr"